#!/usr/bin/env bash
# Guard JoyPlan flow: floating islands, new scene graph, Session still owns SceneIR.
set -euo pipefail
root="$(cd "$(dirname "$0")/../.." && pwd)"

fail() { echo "FAIL: $*" >&2; exit 1; }
has() { grep -q -- "$2" "$1" || fail "$1 missing $2"; }
lacks() { grep -q -- "$2" "$1" && fail "$1 must not contain $2" || true; }

# Boot path
has "$root/godot/project.godot" 'run/main_scene="res://app/main.tscn"'
has "$root/godot/app/main.gd" "res://app/joyplan_flow/home.tscn"
lacks "$root/godot/app/main.gd" "photo_stub"
lacks "$root/godot/app/main.gd" "引导量房"
lacks "$root/godot/app/main.gd" "_place_fab"
lacks "$root/godot/app/main.gd" "attach_hud"

# Island chrome language
has "$root/godot/app/joyplan_flow/islands.gd" "class_name FlowIslands"
has "$root/godot/app/joyplan_flow/islands.gd" "shadow_size"
has "$root/godot/app/joyplan_flow/islands.gd" "mode_capsule"
has "$root/godot/app/joyplan_flow/islands.gd" "green_fab"
has "$root/godot/app/joyplan_flow/islands.gd" "plus_fab"
has "$root/godot/app/joyplan_flow/islands.gd" "bottom_2d_dock"
has "$root/godot/app/joyplan_flow/islands.gd" "green_back_2d"
has "$root/godot/app/joyplan_flow/islands.gd" "right_circles"
has "$root/godot/app/joyplan_flow/islands.gd" "PAGE_GREEN"
lacks "$root/godot/app/joyplan_flow/islands.gd" "JoyplanChrome"
lacks "$root/godot/app/joyplan_flow/islands.gd" "NavBar"

# FSM
has "$root/godot/app/joyplan_flow/router.gd" "SCALE"
has "$root/godot/app/joyplan_flow/router.gd" "EDIT_2D"
has "$root/godot/app/joyplan_flow/router.gd" "EDIT_3D"
has "$root/godot/app/joyplan_flow/router.gd" "ELEVATION"

# S1 — JoyPlan home (我的项目), never a blank pill
has "$root/godot/app/joyplan_flow/home.gd" "我的项目"
has "$root/godot/app/joyplan_flow/home.gd" "AI厨房"
has "$root/godot/app/joyplan_flow/home.gd" "拍照速记Pro"
has "$root/godot/app/joyplan_flow/projects.gd" "工程项目"
has "$root/godot/app/joyplan_flow/projects.gd" "新建项目"
has "$root/godot/app/joyplan_flow/new_plan.gd" "新建户型"
has "$root/godot/app/joyplan_flow/new_plan.gd" "导入户型图"
has "$root/godot/app/joyplan_flow/pick_source_modal.gd" "选择户型图"
has "$root/godot/app/joyplan_flow/pick_source_modal.gd" "相册选择"
has "$root/godot/app/joyplan_flow/pick_source_modal.gd" "拍照上传"
has "$root/godot/app/joyplan_flow/pick_source_modal.gd" "使用示例户型"
has "$root/godot/app/joyplan_flow/import_pick_host.gd" "pick_gallery"
has "$root/godot/app/joyplan_flow/new_plan.gd" "import_pick_host"
has "$root/godot/app/joyplan_flow/edit_2d.gd" "import_pick_host"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "ACTION_GET_CONTENT"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "ACTION_PICK"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "ACTION_PICK_IMAGES"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "cacheImportsDir"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "isChineseOem"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "ClipData"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "onMainResume"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "createNewFile"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "ACTION_IMAGE_CAPTURE"
has "$root/godot/android-plugin/toporoom-media/src/main/AndroidManifest.xml" "READ_MEDIA_IMAGES"
has "$root/godot/android-plugin/toporoom-media/src/main/AndroidManifest.xml" "GET_CONTENT"
has "$root/godot/android-plugin/toporoom-media/src/main/AndroidManifest.xml" "IMAGE_CAPTURE"
has "$root/godot/app/session.gd" "load_gold_sample"
has "$root/godot/app/joyplan_flow/router.gd" "PROJECTS"
has "$root/godot/app/joyplan_flow/router.gd" "NEW_PLAN"
has "$root/godot/app/joyplan_flow/router.gd" "GENERATE"
has "$root/godot/app/joyplan_flow/router.gd" "FREE_DRAW"
has "$root/godot/app/joyplan_flow/router.gd" "SCREEN_FREE_DRAW"
has "$root/godot/app/joyplan_flow/router.gd" "AR_SCAN"
has "$root/godot/app/joyplan_flow/router.gd" "SCREEN_AR_SCAN"
has "$root/godot/app/joyplan_flow/new_plan.gd" "_open_draw"
has "$root/godot/app/joyplan_flow/new_plan.gd" "FlowRouter.free_draw"
has "$root/godot/app/joyplan_flow/new_plan.gd" "_open_ar"
has "$root/godot/app/joyplan_flow/new_plan.gd" "FlowRouter.ar_scan"
has "$root/godot/app/joyplan_flow/ar_scan.gd" "AR扫描"
has "$root/godot/app/joyplan_flow/ar_scan.gd" "add_ar_wall"
has "$root/godot/app/joyplan_flow/ar_scan.gd" "load_demo_room"
has "$root/godot/app/joyplan_flow/ar_scan.gd" "ar_hit_center"
has "$root/godot/app/joyplan_flow/ar_scan.gd" "演示房间"
has "$root/godot/app/session.gd" "func start_ar_scan"
has "$root/godot/app/session.gd" "func add_ar_wall"
has "$root/godot/app/session.gd" "func commit_ar_polyline"
has "$root/godot/app/session.gd" "func ar_demo_rectangle"
has "$root/godot/app/session.gd" "from_ar_scan"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "ar_available"
has "$root/godot/android-plugin/toporoom-media/src/main/java/com/toporoom/plugin/TopoRoomMediaPlugin.java" "ar_hit_center"
has "$root/godot/android-plugin/toporoom-media/src/main/AndroidManifest.xml" "com.google.ar.core"
lacks "$root/godot/app/joyplan_flow/new_plan.gd" 'ar_btn.pressed.connect(func(): _soon())'
has "$root/godot/app/joyplan_flow/new_plan.gd" '手绘草图&房间", "手绘勾勒，户型立现", "✎", func(): _soon()'
has "$root/godot/app/joyplan_flow/free_draw.gd" "自由绘制"
has "$root/godot/app/joyplan_flow/free_draw.gd" "add_drawn_wall"
has "$root/godot/app/joyplan_flow/free_draw.gd" "draw_rectangle_mm"
has "$root/godot/app/joyplan_flow/free_draw.gd" "SNAP_PX"
has "$root/godot/app/joyplan_flow/free_draw.gd" "JoyplanChrome.step_bar"
has "$root/godot/app/session.gd" "func start_free_draw"
has "$root/godot/app/session.gd" "func add_drawn_wall"
has "$root/godot/app/session.gd" "func move_drawn_wall"
has "$root/godot/app/session.gd" "func delete_drawn_wall"
has "$root/godot/app/session.gd" "func undo_draw"
has "$root/godot/app/session.gd" "host.delete_wall"
lacks "$root/godot/app/joyplan_flow/free_draw.gd" "host.add_wall"
lacks "$root/godot/app/joyplan_flow/new_plan.gd" '自由绘制", "使用光标开始绘制新布局", "✎", func(): _soon()'
lacks "$root/godot/app/joyplan_flow/home.gd" 'call_deferred("_open_gallery")'
lacks "$root/godot/app/joyplan_flow/home.gd" "拍户型"
lacks "$root/godot/app/joyplan_flow/home.gd" "_island_cta"
lacks "$root/godot/app/joyplan_flow/home.gd" "选择户型图"

# S2
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" "1/2 临摹图比例"
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" "请输入标注线的实际长度"
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" "下一步"
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" '"900"'
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" "LOUPE_ZOOM"
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" "_draw_loupe_cross"
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" "import_photo_vision"
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" "_on_overlay_input"
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" "HANDLE_HIT"
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" "_cover_rect"
has "$root/godot/app/joyplan_flow/scale_calibrate.gd" "_to_overlay_local"
has "$root/godot/app/plan_canvas.gd" "_vision_registration"
has "$root/godot/app/plan_canvas.gd" "origin_x_px"
has "$root/godot/app/plan_canvas.gd" "_photo_ink_ratio"
has "$root/godot/extension/src/toporoom_host.cpp" "origin_x_px"
has "$root/godot/app/joyplan_flow/generate_space.gd" "2/2 生成空间"

# S3 / S4
has "$root/godot/app/joyplan_flow/edit_2d.gd" "mode_compass"
has "$root/godot/app/joyplan_flow/islands.gd" "mode_compass"
has "$root/godot/app/joyplan_flow/islands.gd" "ModeCompass"
has "$root/godot/app/joyplan_flow/edit_2d.gd" "green_fab"
has "$root/godot/app/joyplan_flow/edit_2d.gd" "ctx_pill"
has "$root/godot/app/joyplan_flow/islands.gd" "mode_capsule"
has "$root/godot/app/plan_canvas.gd" "PAGE_SELECT"
has "$root/godot/app/joyplan_flow/edit_2d.gd" "翻转"
has "$root/godot/app/joyplan_flow/edit_2d.gd" "复制"
has "$root/godot/app/joyplan_flow/edit_2d.gd" "删除"
has "$root/godot/app/joyplan_flow/edit_2d.gd" "导入户型图"
has "$root/godot/app/joyplan_flow/edit_2d.gd" "_show_add_menu"
has "$root/godot/app/joyplan_flow/library_sheet.gd" "收藏"
has "$root/godot/app/joyplan_flow/library_sheet.gd" "门"
has "$root/godot/app/joyplan_flow/library_sheet.gd" "窗"
has "$root/godot/app/joyplan_flow/library_sheet.gd" "梁管"
has "$root/godot/app/joyplan_flow/library_sheet.gd" "电气"
has "$root/godot/app/joyplan_flow/library_sheet.gd" "长按控件拖到平面图"
has "$root/godot/app/plan_canvas.gd" "_draw_drag_dim"
has "$root/godot/app/plan_canvas.gd" "_format_area_m2"
has "$root/godot/app/plan_canvas.gd" "m²"
has "$root/godot/app/plan_canvas.gd" "joyplan_look"

# S5–S7
has "$root/godot/app/joyplan_flow/edit_3d.gd" "mode_compass"
has "$root/godot/app/joyplan_flow/edit_3d.gd" "plus_fab"
has "$root/godot/app/joyplan_flow/edit_3d.gd" "right_circles"
has "$root/godot/app/joyplan_flow/edit_3d.gd" "Session.move_shared_vertex"
has "$root/godot/app/joyplan_flow/edit_3d.gd" "Session.update_opening_geom"
has "$root/godot/app/joyplan_flow/edit_3d.gd" "_place_opening_at"
has "$root/godot/app/joyplan_flow/edit_3d.gd" "_tween_extrude"
has "$root/godot/app/joyplan_flow/minimap.gd" "FOV"
has "$root/godot/app/joyplan_flow/ruler_sheet.gd" "Ruler display"
has "$root/godot/app/joyplan_flow/ruler_sheet.gd" "Dimensions"
has "$root/godot/app/joyplan_flow/edit_3d.gd" "PAGE_DIM"

# S8
has "$root/godot/app/joyplan_flow/elevation_index.gd" "Elevation Index"

# No old chrome on the run path
lacks "$root/godot/app/joyplan_flow/edit_3d.gd" "attach_hud"
lacks "$root/godot/app/joyplan_flow/edit_2d.gd" "_place_fab"
lacks "$root/godot/app/joyplan_flow/home.gd" "Studio.nav_bar"

# Session still owns vision / demolition
has "$root/godot/app/session.gd" "import_photo_fake"
has "$root/godot/app/session.gd" "import_photo_vision"
has "$root/godot/app/session.gd" "store_imported_image"
has "$root/godot/app/session.gd" "demolish_wall"
has "$root/godot/app/session.gd" "func flip_opening"
has "$root/godot/app/media_picker.gd" "TopoRoomMedia"
has "$root/godot/export_presets.cfg" "permissions/camera=true"
has "$root/godot/export_presets.cfg" "VIBRATE"
has "$root/godot/export_presets.cfg" "app/_legacy/"

# Tokens
has "$root/godot/app/theme/tokens.gd" "3478F6"
has "$root/godot/app/theme/tokens.gd" "PAGE_ISLAND"
has "$root/godot/app/theme/tokens.gd" "PAGE_GREEN"
lacks "$root/godot/app/theme/tokens.gd" "C45C26"

echo "OK: JoyPlan flow scene graph / island chrome invariants"
